INSERT INTO TBL_CATEGORY (ID,NAME)  VALUES (1,'Fabricação Própria');
INSERT INTO TBL_CATEGORY (ID,NAME)  VALUES (2,'Nacional');
INSERT INTO TBL_CATEGORY (ID,NAME)  VALUES (3,'Importado');
INSERT INTO TBL_CATEGORY (ID,NAME)  VALUES (4,'Premium');

INSERT
INTO TBL_PRODUCT(ID,NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES(1,'Computador XP','I9,SSD500,HD1T, 32GB', 5999.99,1,true,true);          

INSERT
INTO TBL_PRODUCT(ID,NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES(2,'Computador XR','I7,SSD500,HD1T, 16GB', 4999.99,2,true,false);  

INSERT
INTO TBL_PRODUCT(ID,NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES(3,'Computador XR','I7,SSD256,HD1T, 16GB', 4599.99,3,false,false);  

INSERT
INTO TBL_PRODUCT(ID,NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES(4,'Computador XR','I7, HD1T, 16GB', 4000,4,false,false);  